# Generated by Django 4.0 on 2022-09-15 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_year', models.IntegerField()),
                ('experience_level', models.CharField(max_length=5)),
                ('employment_type', models.CharField(max_length=5)),
                ('job_title', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
                ('salary_currency', models.CharField(max_length=10)),
                ('salary_in_usd', models.IntegerField()),
                ('employee_residence', models.CharField(max_length=100)),
                ('remote_ratio', models.IntegerField()),
                ('company_location', models.CharField(max_length=200)),
                ('company_size', models.IntegerField()),
            ],
        ),
    ]
